### ISSUE TITLE
SuiteSparse is officially on Github now

### ISSUE THREAD

**Issue by ecsx1** [jluttine/suitesparse#11]
When you google `suitesparse github` this repo is the first result.
It was created as a mirror for SuiteSparse when SuiteSparse wasn't available on Github.
But now Tim Davis put it officially here: https://github.com/DrTimothyAldenDavis/SuiteSparse.
Keeping this repo only causes confusion. Please consider it for deletion.
Thank you.

**Comment by jluttine** [comment]
Thanks for the info, really glad to hear that! Yes, I will close this repo and/or see if I can make it forward automatically to the official repository.

**Comment by ecsx1** [comment]
Thanks for keeping this repo updated for all the time.
It's been useful. But it's even better now that there's Tim Davis came with an official repo here.

**Comment by jluttine** [comment]
I now updated the repo description and README. I'll archive this repository. I couldn't figure out a way to automatically forward a repository URL to another, so I'll archive this instead of deleting. Otherwise, some links or workflows around the internet might suddenly break. But if there's a way to automatically forward to another repo, I'm happy to make that change.
